package jasper.command;

/**
 * Represents the result of executing a command.
 *
 * @param commandType The type of command that was executed.
 * @param response The response message generated by the command execution.
 */
public record CommandResult(CommandType commandType, String response) {
    /**
     * Returns whether this command result indicates the application should quit.
     *
     * @return True if the command type is a quit command, false otherwise.
     */
    public boolean isQuit() {
        return commandType().equals(CommandType.QUIT);
    }
}
